### ISSUE TITLE
Need a proper documentation on Using the HUB

### ISSUE THREAD

**Issue by dhoomakethu** [boakley/robotframework-hub#37]
Hi,

I have been trying a lot to get the hub working for my robot test suite with out any success. 
The docuementation "Want to browse your local robotframework assets? Just include the path to your test suites or resource files on the command line:

```
$ python -m rfhub /path/to/test/suite"  is not helping much.
```

If i try to pass the root folder path of my test suite as above where in I have my resource file in .tsv format,which in turn includes the actual resource files and library import information ,it just loops through all the subfolders and prints exclude_patterns: []. when i open http://localhost:7070/doc/ , I just see the documentation of the standard robot libraries and not the test libraries I have.

Am i missing something here or the rfhub does not support the tsv format yet ?

I would love to have a proper docuementation on how to use this cool project.
Regards
sanjay

**Comment by cdeng** [comment]
@boakley I saw you had some code for .rfhubignore, is it fully implemented yet?  Thanks.

**Comment by boakley** [comment]
No, I'm sorry, I haven't finished with the implementation of that feature
yet.

--bryan
