### ISSUE TITLE
RF HUB with more external libraries

### ISSUE THREAD

**Issue by GayanaYJ** [boakley/robotframework-hub#40]
Hi ,

I see that RF hub has few libraries which is very useful in knowing the keywords. I am using the keywords from httpLibrary. Is there any way to get RF HUB get updated with external library HTTPLibrary ?
Please let me know

**Comment by boakley** [comment]
After I reread your first comment, it appears you want auto-complete in the shell window where you're starting the hub. I have no control over the shell window. 

I don't think there's anything here I can fix.
