### ISSUE TITLE
support for pythonpath installed ressources

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [boakley/robotframework-hub#50]
at work we ship common ressources together with a python library,
however the hub doesnt support listing those

**Comment by boakley** [comment]
The hub already supports this. For example, if I create a file named `customkeywords.py` in a folder, put that folder on PYTHONPATH, and then give the name `customkeywords` to the hub, it will find the keywords

    $ export PYTHONPATH=/tmp
    ...
    $ python -m rfhub customkeywords

**Comment by RonnyPfannschmidt** [comment]
i'm talking about *.robot files, not python modules, python modules already wok fabulous

**Comment by RonnyPfannschmidt** [comment]
basially we have a structure that looks like:
```
ourlib/__init__.py # python keywords
ourlib/resources/common/foo_control.robot  # robot keywords in text fomrat that are shared
....
```

**Comment by niravsh** [comment]
We have .txt resource files and as long as they are specified correctly, the hub finds all keywords fine.

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
