### ISSUE TITLE
Run rfhub in production webserver

### ISSUE THREAD

**Issue by jjb0385** [boakley/robotframework-hub#51]
How could rfhub be configured to be run out of gunicorn or another webserver?

**Comment by boakley** [comment]
I do not know. I've never used gunicorn or had the need to run it with another webserver.

**Comment by jjb0385** [comment]
What is your recommendation for having an instance of this running constantly?
Just fire up 'python -m rfhub' and leave it running?
Are there any memory/performance concerns or should that be good?

**Comment by boakley** [comment]
That's how it was designed to be used - just leave it running

**Comment by jjb0385** [comment]
Great -- it wasn't totally clear that was the intention for long running instances.
Thanks!
