### ISSUE TITLE
Help needed for Soap API Automation using robot framework

### ISSUE THREAD

**Issue by sudharani08** [boakley/robotframework-hub#61]
We are trying to automate soap api automation using suds but very first step of authentication is not happening i am using SudsLibrary keywords as follow.

    Create Soap Client       http://localhost:8084/prefchoice-api-v3/soap?WSDL
    Set Http Authentication      BrickhouseUser       BrickhouseUser      ALWAYS_SEND  

Can some one help me with this

**Comment by boakley** [comment]
This ticket has nothing to do with the robotframework hub.

**Comment by charleshamel73** [comment]
http://stackoverflow.com/questions/18175489/python-soap-using-requests. if your using robot framework, just created a Python class and create methods in there.
