### ISSUE TITLE
Module import does not work

### ISSUE THREAD

**Issue by aaltat** [boakley/robotframework-hub#66]
When I start rfhub like this: `python -m rfhub --pythonpath C:\path\to\libs --module server.login_page.login.Login`. Then I get error: `unable to import 'server.login_page.login.Login' : No module named Login` 

The `--pythonpath C:\path\to\libs` is same as in my pybot startup script and `server.login_page.login.Login` is in the same way is I import the library in Robot data. I do not understand why the rfhub is not able to parse the library.

**Comment by boakley** [comment]
is server.login_page.login.Login a module, or is "Login" a class in the
"login" module? In other words, does the file
\path\to\libs\server\login_page\login\Login.py exist?

**Comment by aaltat** [comment]
I am home but I am pretty sure that Login is a class in the login.py file.

**Comment by aaltat** [comment]
Would solving the problem be easier if there would be an example?

**Comment by boakley** [comment]
The --module argument, as the name implies, requires a module rather than a
class. Try it with '--module server.login_page.login'. It should then find
all classes in that module.

**Comment by aaltat** [comment]
And if the module contains many classes but it should find only a one class, the Login. Then I should give the command like:  `python -m rfhub --pythonpath C:\path\to\libs --module server.login_page.login Login`

**Comment by boakley** [comment]
No, --module means "find all the classes in this module". It's primarily
designed for a module that defines page objects, or a module that defines
several collections of keywords.

If you want only a specific class, use "--library
server.login_page.login.Login".

**Comment by aaltat** [comment]
Ah ok, thanks for info

**Comment by aaltat** [comment]
Tried and works like a charm. Thanks from input.

**Comment by boakley** [comment]
Thanks for using the hub! I hope you're finding it helpful. I wish I had
more time to make it better :-\

**Comment by aaltat** [comment]
It is really useful, it makes finding the keywords so easy. Keep up the good work.
