### ISSUE TITLE
Need to support python3

### ISSUE THREAD

**Issue by boakley** [boakley/robotframework-hub#78]
If you try to install with python3 you will get the following error:

```
File "C:\...\robotframework-hub\setup.py", line 5, in <module>
        execfile('rfhub/version.py')
    NameError: name 'execfile' is not defined
```

If you run directly from the repository, `python3 -m rfhub ...` gives the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/boakley/Dropbox/git/robotframework-hub/rfhub/__init__.py", line 4, in <module>
    import kwdb
ImportError: No module named 'kwdb'

```

**Comment by joaonc** [comment]
Indeed without Python 3 support this project will soon be dead..   it appears this repo is no longer maintained.

Does anyone know of a fork to this project that's actively updated?

This is a really cool project and would be a shame to let it die  😞

**Comment by boakley** [comment]
I hope to be able to dedicate some time to it during my vacation in a
couple of weeks.

**Comment by louislewatcn** [comment]
Hi, I have used Fitnesse for a long time , which is a web based key-word test framework of Java.
But the requirements is JDK1.6 , and I want to find an alternative. 
It seems it is very good one but it is not ready yet.
You planning is amazing as Fitnesse functions
If need more suggestion on it,  is to include integrate Sikuli (image recognition) simple API such as click an image on screen  or remote screen (/path/to/image), and verify (/path/to/image) on screen or remote screen.
Very glad to see your project here.

**Comment by joaonc** [comment]
Any chance this will happen?
To make things easier, you could even drop python 2 support for the newer versions and folks on P2 would use the current version.

**Comment by boakley** [comment]
sorry, I just haven't had much time. I've done the work, I just haven't had
time to test it and package it up and create new version for pypi.

**Comment by ziame** [comment]
There is a pull request fixing that -- it's about the imports. Python3 works a tad differently in that regard.

**Comment by joaonc** [comment]
Any luck finding the time for this @boakley ?

**Comment by Rue1983** [comment]
Just looking for a solution. As long as it supports python3 I think everyone will be glad to improve it.

**Comment by MaciejWiczk** [comment]
> Just looking for a solution. As long as it supports python3 I think everyone will be glad to improve it.

>Any luck finding the time for this @boakley ?

Hi Guys. I hope @boakley, wouldn't mind that I mention alternative/ fully python 3 solution [rfhub2](https://github.com/pbylicki/rfhub2). It's in early stage, but it should work on most of the cases.

**Comment by james-powis** [comment]
We are 19 days from python2 ending support, and also my corporate requirements dictate everything must be under some level of support... Is there any hope of having this functional under ptyhon3 by end of Year? I see RF Hub2 is out there as a competing standard.

I can get this running in a container, but all the imports throw exceptions due to all libraries now being exclusively python3 compliant.

**Comment by boakley** [comment]
The code in the github repo works with python3. I simply haven't pushed a
new version to pypi.

**Comment by boakley** [comment]
version 1.0 is out, and it requires python 3
